services:
  - type: web
    name: speech-translator-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: ALLOWED_ORIGINS
        value: ""
